### ISSUE TITLE
Add Ability to Hide Tray Icon

### ISSUE THREAD

**Issue by artistro08** [sigoden/windows-switcher#13]
Would be pretty awesome to add the ability to remove the tray icon if a flag or file is in the same folder of the app.

**Comment by sigoden** [comment]
win10 already supports hidden tray。

**Comment by artistro08** [comment]
What about win11?

**Comment by artistro08** [comment]
Also, i mean completely hidden. Not in the tray overflow at all.

**Comment by sigoden** [comment]
Why needs to be completely hidden?

The trayicon is used to indicate that the windows switcher is running, provides some userful shortcuts.
