### ISSUE TITLE
Request: Blacklist processes by name

### ISSUE THREAD

**Issue by robmonte** [sigoden/windows-switcher#17]
I think it would be useful to be able to define a process blacklist, where Windows-Switcher will _not_ perform a window switch upon press and instead pass the hotkey along to the focused application. Currently Windows-Switcher eats the hotkey press when there are no windows to switch between.

Example:
1. I set the hotkey to ctrl+space
2. I load up a game that uses ctrl+space for crouch-jumping
3. I specify `game.exe` in a blacklist.txt file located in the same directory as windows-switcher.exe
4. In the game, when I hold ctrl and press space, it performs a jump.

The current behavior in this scenario is that no action at all happens in-game.

## Alternate behavior to consider

Another consideration is that when there is only a single window for an application, pressing the hotkey could pass it to the focused window regardless of a blacklist or not. Perhaps this could be toggleable behavior.

**Comment by robmonte** [comment]
@sigoden Thank you so much for implementing this! I was wondering if also includes the "alternate behavior" I mentioned or if it was only the blacklist?

**Comment by sigoden** [comment]
Only apps in the blacklist will be excluded。

alternate behavior is not reasonable.

For example, in WindowsTerminal.exe, if the hotkey ``` alt+` ``` is transparently passed, the page will be displayed as follows
![image](https://user-images.githubusercontent.com/4012553/219829367-0afc74fd-d4ae-4cc4-82cd-70b9fe02af49.png)

it's annoying.
