### ISSUE TITLE
v0.7.0 rc3 seems to crash on start

### ISSUE THREAD

**Issue by robmonte** [sigoden/windows-switcher#26]
Trying to launch the v0.7.0 release candidate crashes immediately for me. Not sure what other info I can provide as I don't see a way to get logs or anything.

**Comment by sigoden** [comment]
I apologize for the inconvenience caused to you. But I downloaded it and tried it and found no problem.

In v0.7.0-rc4, I added startup error messgebox warning and log to file. You can try to find the problem.

**Comment by robmonte** [comment]
You're right the issue was on my end. The error told me that I had some other process taking the keyboard shortcut that I wasn't aware was using it. The error box was very helpful otherwise I'd never have found that!
